"""
Chafa integration.

Provides image rendering using the chafa command.
"""

import shutil
import subprocess


class Chafa:
    """
    Render images using Chafa.
    """

    DEFAULT_CONFIG = {
        "command": "chafa",

        "format": "symbols",
        "colors": "full",
        "optimize": 0,

        "font_ratio": "1/2",
        "symbols": "block+border+space-wide",

        "polite": True,
    }

    def __init__(self, options=None):
        options = options or {}

        self.config = self.DEFAULT_CONFIG.copy()
        self.config.update(options)

    # ========================================================================
    # STATE
    # ========================================================================

    def is_installed(self):
        """
        Check whether Chafa is available.
        """
        return shutil.which(
            self.config["command"]
        ) is not None

    # ========================================================================
    # CONFIGURATION
    # ========================================================================

    def get_config(self):
        """
        Return a copy of the current configuration.
        """
        return self.config.copy()

    # ========================================================================
    # VALIDATION
    # ========================================================================

    @staticmethod
    def _validate_size(size):
        """
        Validate an image size.
        """
        if not isinstance(size, dict):
            return False

        try:
            width = int(size["width"])
            height = int(size["height"])
        except (
            KeyError,
            TypeError,
            ValueError,
        ):
            return False

        return (
            width > 0
            and height > 0
        )

    # ========================================================================
    # COMMAND
    # ========================================================================

    def _command(self, image, size):
        """
        Build the Chafa command.
        """
        width = int(size["width"])
        height = int(size["height"])

        return [
            self.config["command"],

            "--format",
            str(self.config["format"]),

            "--colors",
            str(self.config["colors"]),

            "--optimize",
            str(self.config["optimize"]),

            "--font-ratio",
            str(self.config["font_ratio"]),

            "--symbols",
            str(self.config["symbols"]),

            "--polite",
            "on" if self.config["polite"] else "off",

            "--size",
            f"{width}x{height}",

            image,
        ]

    # ========================================================================
    # COLORS
    # ========================================================================

    @staticmethod
    def _rgb_to_hex(r, g, b):
        """
        Convert RGB values into a hexadecimal color.
        """
        r = max(
            0,
            min(
                255,
                int(r),
            ),
        )

        g = max(
            0,
            min(
                255,
                int(g),
            ),
        )

        b = max(
            0,
            min(
                255,
                int(b),
            ),
        )

        return f"#{r:02x}{g:02x}{b:02x}"

    # ========================================================================
    # ANSI PARSER
    # ========================================================================

    def _parse_ansi(self, output):
        """
        Parse ANSI SGR output generated by Chafa.

        Returns:

            lines
            highlights
        """

        lines = []
        highlights = []

        current_fg = None
        current_bg = None

        line = []
        line_index = 0
        byte_column = 0

        def push_line():
            nonlocal line
            nonlocal byte_column
            nonlocal line_index

            lines.append(
                "".join(line)
            )

            line = []
            byte_column = 0
            line_index += 1

        def add_char(char):
            nonlocal byte_column

            if not char:
                return

            start_col = byte_column

            line.append(char)

            byte_column += len(
                char.encode("utf-8")
            )

            if (
                current_fg is not None
                or current_bg is not None
            ):
                highlights.append({
                    "line": line_index,
                    "start_col": start_col,
                    "end_col": byte_column,
                    "fg": current_fg,
                    "bg": current_bg,
                })

        def parse_sgr(parameters):
            nonlocal current_fg
            nonlocal current_bg

            if not parameters:
                values = [0]

            else:
                values = []

                for value in parameters.split(";"):
                    try:
                        values.append(
                            int(value)
                        )
                    except ValueError:
                        values.append(0)

            index = 0

            while index < len(values):
                code = values[index]

                # Reset.
                if code == 0:
                    current_fg = None
                    current_bg = None

                # Default foreground.
                elif code == 39:
                    current_fg = None

                # Default background.
                elif code == 49:
                    current_bg = None

                # Truecolor foreground.
                elif (
                    code == 38
                    and index + 4 < len(values)
                    and values[index + 1] == 2
                ):
                    r = values[index + 2]
                    g = values[index + 3]
                    b = values[index + 4]

                    current_fg = self._rgb_to_hex(
                        r,
                        g,
                        b,
                    )

                    index += 4

                # Truecolor background.
                elif (
                    code == 48
                    and index + 4 < len(values)
                    and values[index + 1] == 2
                ):
                    r = values[index + 2]
                    g = values[index + 3]
                    b = values[index + 4]

                    current_bg = self._rgb_to_hex(
                        r,
                        g,
                        b,
                    )

                    index += 4

                index += 1

        def get_utf8_char(data, position):
            first_byte = data[position]

            # ASCII.
            if first_byte < 0x80:
                return (
                    chr(first_byte),
                    1,
                )

            # 2-byte character.
            if 0xC0 <= first_byte <= 0xDF:
                length = 2

            # 3-byte character.
            elif 0xE0 <= first_byte <= 0xEF:
                length = 3

            # 4-byte character.
            elif 0xF0 <= first_byte <= 0xF4:
                length = 4

            else:
                return (
                    chr(first_byte),
                    1,
                )

            chunk = data[
                position:position + length
            ]

            try:
                return (
                    chunk.decode(
                        "utf-8"
                    ),
                    length,
                )

            except UnicodeDecodeError:
                return (
                    chr(first_byte),
                    1,
                )

        # Work with bytes so byte offsets match
        # Neovim's buffer column expectations.
        data = output.encode("utf-8")

        position = 0
        length = len(data)

        while position < length:

            # ---------------------------------------------------------------
            # ANSI CSI sequence
            # ---------------------------------------------------------------

            if (
                data[position] == 0x1B
                and position + 1 < length
                and data[position + 1] == ord("[")
            ):
                end = position + 2

                while end < length:
                    byte = data[end]

                    if 0x40 <= byte <= 0x7E:
                        break

                    end += 1

                if end < length:

                    parameters = data[
                        position + 2:end
                    ].decode(
                        "ascii",
                        errors="ignore",
                    )

                    final = chr(
                        data[end]
                    )

                    if final == "m":
                        parse_sgr(
                            parameters
                        )

                    position = end + 1

                    continue

            # ---------------------------------------------------------------
            # Newline
            # ---------------------------------------------------------------

            if data[position] == ord("\n"):
                push_line()

                position += 1

                continue

            # ---------------------------------------------------------------
            # UTF-8 character
            # ---------------------------------------------------------------

            char, char_length = (
                get_utf8_char(
                    data,
                    position,
                )
            )

            add_char(char)

            position += char_length

        # Flush final line.
        if line or not lines:
            push_line()

        return lines, highlights

    # ========================================================================
    # RENDER
    # ========================================================================

    def render(
        self,
        image,
        size,
    ):
        """
        Render an image synchronously.

        Returns:

            {
                "lines": [...],
                "highlights": [...]
            }

        Raises:

            ValueError
            RuntimeError
        """

        if not isinstance(
            image,
            str,
        ) or not image:
            raise ValueError(
                "Invalid image path"
            )

        if not self._validate_size(size):
            raise ValueError(
                "Invalid image size"
            )

        if not self.is_installed():
            raise RuntimeError(
                "Chafa is not installed"
            )

        command = self._command(
            image,
            size,
        )

        try:
            result = subprocess.run(
                command,
                capture_output=True,
                text=False,
                check=False,
            )

        except OSError as error:
            raise RuntimeError(
                str(error)
            ) from error

        if result.returncode != 0:
            error = result.stderr.decode(
                "utf-8",
                errors="replace",
            ).strip()

            raise RuntimeError(
                error or "Chafa failed"
            )

        output = result.stdout.decode(
            "utf-8",
            errors="replace",
        )

        lines, highlights = (
            self._parse_ansi(
                output
            )
        )

        return {
            "lines": lines,
            "highlights": highlights,
        }

